#!/bin/sh
# This is file 'vc' from the vc bundle for TeX.
# The original file can be found at CTAN:support/vc.
# This file is Public Domain.

# Parse command line options.
full=0
mod=0
while [ -n "$(echo $1 | grep '-')" ]; do
    case $1 in 
       -f ) full=1 ;;
       -m ) mod=1 ;;
       *  ) echo 'usage: vc [-f] [-m]'
            exit 1
    esac
    shift
done
# English locale.
LC_ALL=C
COMMIT_MSG=`git --no-pager log -1 HEAD --pretty=format:"%s"`
# Skip merge of branch master commits
if [ "$COMMIT_MSG" = "Merge branch 'master' of ssh://git.sep2011.de/git/sep2011" ] || [ "$COMMIT_MSG" = "Merge branch 'master' of ssh://git.sep2011.de/git/funCKit" ] || [ "$COMMIT_MSG" = "Merge branch 'master' of ssh://sep2011/git/funCKit" ]; then
	git --no-pager log -1 HEAD~1 --pretty=format:"Hash: %H%nAbr. Hash: %h%nParent Hashes: %P%nAbr. Parent Hashes: %p%nAuthor Name: %an%nAuthor Email: %ae%nAuthor Date: %ai%nCommitter Name: %cn%nCommitter Email: %ce%nCommitter Date: %ci%nCommit Message: %s%n" |gawk -v script=log -v full=$full -f vc-git.awk > vc.tex
else
	git --no-pager log -1 HEAD --pretty=format:"Hash: %H%nAbr. Hash: %h%nParent Hashes: %P%nAbr. Parent Hashes: %p%nAuthor Name: %an%nAuthor Email: %ae%nAuthor Date: %ai%nCommitter Name: %cn%nCommitter Email: %ce%nCommitter Date: %ci%nCommit Message: %s%n" |gawk -v script=log -v full=$full -f vc-git.awk > vc.tex
fi
if [ "$mod" = 1 ]
then
  git status |gawk -v script=status -f vc-git.awk >> vc.tex
fi
